// app/layout.tsx
import type { Metadata } from "next";

import { cookieToInitialState } from "wagmi";

import { config } from "../config";
import Web3ModalProvider from "../context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config);
  return (
    <Web3ModalProvider initialState={initialState}>
      {children}
    </Web3ModalProvider>
  );
}
